# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDdd():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ddd(self):
    self.driver.get("http://openncart.herokuapp.com/")
    self.driver.set_window_size(1440, 790)
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").click()
    element = self.driver.find_element(By.NAME, "search")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").click()
  
